echo "OPEN YAML: /Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/19-snow-connector-workflow-again/1-open-snow-connector-and-pd.workflow.yaml"
echo "CLOSE YAML: /Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/19-snow-connector-workflow-again/2-close-snow-connector-and-pd.workflow.yaml"
echo "Map ServiceNow Connection to https://silvastg.service-now.com on all snow tasks"
echo "Classic servicenowstg: set ITSM OFF; ITOM optional"
echo "Allowlist: silvastg.service-now.com and events.pagerduty.com"
echo "Replace __PD_ROUTING_KEY__ and SNOW assignMap sys_ids before activate"
echo "Sync key: correlation_id = dedup_key = dt-problem-<problemId>"
ls "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/19-snow-connector-workflow-again"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" add "app/Adocs/2026-09-17/19-snow-connector-workflow-again"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" status --short "app/Adocs/2026-09-17/19-snow-connector-workflow-again"
echo "Do not commit/push unless user asks"
