echo "Captured: P260120F Splunk to Dynatrace Gate2 Build+Cloud Permit ARB 2026/06/26"
echo "Presenter: ROA Rosel (Ops Middleware and Monitoring); LoB OneAXA; Cost 25M Yen Gate2; Prod Q3-2026"
echo "AS-IS: OpenPaaS/Lambda->S3->Splunk MPI; TO-BE: sources->Dynatrace SaaS AXA-GO; Ex-ADL in scope"
echo "Data: Ingestion->Store->Query; retention 3mo default; MyAXA example 1 year"
echo "Security: OneAccount SSO + RBAC to Dynatrace console (AXA-GO provided)"
echo "History: PA 2026/05/15 done; BP 2026/06/26 THIS ARB; Security Review TBA on summary"
echo "Gaps not in photos: full Impacted Apps list, Decommission Plan, Cloud Binding checklist, IR/CP dates"
echo "git add /Users/k/Codes/Pra/P1GithubActions/P1Gactions/app/Adocs/2026-08-31/10-axa-arb-splunk-dynatrace-migration"
echo "git -C /Users/k/Codes/Pra/P1GithubActions/P1Gactions commit -m \"Add AXA ARB Splunk to Dynatrace migration capture\""
echo "git -C /Users/k/Codes/Pra/P1GithubActions/P1Gactions push"
