# Step-by-step SNOW+PD workflow setup + permissions
echo "1) IAM: automation:workflows:read/write/run + app-engine:apps:run + app-engine:functions:run + app-settings:objects:read/write"
echo "2) Workflows → Settings → Authorization settings → enable app-settings:objects:read"
echo "3) Settings → Connections → ServiceNow → create connection; share Can view"
echo "4) PagerDuty → Events API v2 routing_key"
echo "5) External requests → allow service-now.com and events.pagerduty.com"
echo "6) Upload YAML/JSON from Daily Files/2026-09-13/4-snow-pd-workflow-yaml-and-json/"
echo "7) Replace placeholders or swap to ServiceNow Create Incident action; activate; test Problem open/close"
echo "Docs → https://docs.dynatrace.com/docs/analyze-explore-automate/workflows/security"
echo "Docs → https://docs.dynatrace.com/docs/analyze-explore-automate/workflows/default-workflow-actions/actions/service-now"
