echo "Glance explain: /Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-23/9-four-agents-at-a-glance-explain/9-four-agents-at-a-glance-explain.md"
ls "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-23/9-four-agents-at-a-glance-explain"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" add "app/Adocs/2026-09-23/9-four-agents-at-a-glance-explain"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" status --short "app/Adocs/2026-09-23/9-four-agents-at-a-glance-explain"
echo "Do not commit/push unless user asks"
