curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_db_object?sysparm_query=nameLIKEservice&sysparm_fields=name,label,super_class&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=200" | jq -r '.result[] | [.name,.label,.super_class] | @tsv'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_dictionary?sysparm_query=name=service_offering%5EelementISNOTEMPTY&sysparm_fields=element,column_label,internal_type,reference&sysparm_limit=500" | jq -r '.result[] | [.element,.column_label,.internal_type,.reference] | @tsv'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_dictionary?sysparm_query=name=cmdb_ci_service%5EelementISNOTEMPTY&sysparm_fields=element,column_label,internal_type,reference&sysparm_limit=500" | jq -r '.result[] | [.element,.column_label,.internal_type,.reference] | @tsv'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_choice?sysparm_query=name=incident%5Eelement=u_environment%5Einactive=false&sysparm_fields=label,value&sysparm_limit=100" | jq -r '.result[] | [.label,.value] | @tsv'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci?sysparm_query=name=ts12.hk.intraxa%5EORname=ts12%5EORfqdn=ts12.hk.intraxa&sysparm_fields=sys_id,name,fqdn,sys_class_name,install_status,used_for,support_group&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/svc_ci_assoc?sysparm_query=ci_id.name=ts12.hk.intraxa&sysparm_fields=ci_id.name,service_id.name,service_id.support_group,service_id.used_for&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/cmdb_rel_ci?sysparm_query=child.name=ts12.hk.intraxa&sysparm_fields=parent.name,parent.sys_class_name,type,child.name&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci_service?sysparm_query=name=Third%20Party%20Services%20Monitoring%20Application&sysparm_fields=sys_id,name,sys_class_name,used_for,operational_status,support_group,managed_by_group&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci_service?sysparm_query=nameLIKEfscd%5EORDERBYname&sysparm_fields=name,used_for,operational_status,support_group&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq -r '.result[] | [.name,.used_for,.operational_status,.support_group] | @tsv'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/service_offering?sysparm_query=parent.name=uk-sap-fscd-dev&sysparm_fields=name,u_environment,support_group,company,parent.name&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/service_offering?sysparm_query=ORDERBYparent.name&sysparm_fields=parent.name,u_environment,name,support_group&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=10000" | jq -r '.result[] | [.["parent.name"],.u_environment,.name,.support_group] | @tsv'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_user_group?sysparm_query=name=InfraSupport_Dist-WindowsHK_L2_ASIA&sysparm_fields=sys_id,name,active,manager,email&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_user_group?sysparm_query=active=true%5EnameLIKEAXAJP%5EORDERBYname&sysparm_fields=name,sys_id&sysparm_limit=500" | jq -r '.result[] | [.name,.sys_id] | @tsv'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_user?sysparm_query=nameLIKEShuge&sysparm_fields=sys_id,name,user_name,email,active" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/cmdb/instance/cmdb_ci_server?sysparm_query=name=ts12.hk.intraxa" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/cmdb/instance/cmdb_ci_server/__SERVER_SYS_ID__" | jq '.result | {name: .attributes.name, outbound: [.outbound_relations[] | {type: .type.display_value, target: .target.display_value}], inbound: [.inbound_relations[] | {type: .type.display_value, target: .target.display_value}]}'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/cmdb/meta/cmdb_ci_service" | jq '.result.attributes[] | {element, label, type}'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/stats/service_offering?sysparm_count=true" | jq '.result.stats.count'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/stats/service_offering?sysparm_count=true&sysparm_group_by=u_environment&sysparm_display_value=true" | jq -r '.result[] | [.groupby_fields[0].display_value, .stats.count] | @tsv'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/stats/service_offering?sysparm_count=true&sysparm_group_by=parent&sysparm_display_value=true&sysparm_order_by=parent" | jq -r '.result[] | [.groupby_fields[0].display_value, .stats.count] | @tsv'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/stats/svc_ci_assoc?sysparm_count=true&sysparm_group_by=service_id&sysparm_display_value=true" | jq -r '.result[] | [.groupby_fields[0].display_value, .stats.count] | @tsv'
curl -s -I -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/svc_ci_assoc?sysparm_limit=1" | grep -i x-total-count
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/svc_ci_assoc?sysparm_query=ORDERBYci_id.name&sysparm_fields=ci_id.name,ci_id.fqdn,ci_id.support_group,service_id.name,service_id.support_group,service_id.used_for&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=10000&sysparm_offset=0" | jq -r '["host","host_fqdn","host_support_group","business_service","service_support_group","service_used_for"], (.result[] | [.["ci_id.name"],.["ci_id.fqdn"],.["ci_id.support_group"],.["service_id.name"],.["service_id.support_group"],.["service_id.used_for"]]) | @csv' > silva_ci_service.csv
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/service_offering?sysparm_query=ORDERBYparent.name&sysparm_fields=name,u_environment,support_group,company,parent.name,parent.used_for,parent.support_group&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=10000" | jq -r '["offering","offering_environment","offering_support_group","company","business_service","service_used_for","service_support_group"], (.result[] | [.name,.u_environment,.support_group,.company,.["parent.name"],.["parent.used_for"],.["parent.support_group"]]) | @csv' > silva_offerings_env.csv
open "https://silvastg.service-now.com/svc_ci_assoc_list.do?CSV"
open "https://silvastg.service-now.com/service_offering_list.do?EXCEL"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/incident?sysparm_query=number=INC30339746&sysparm_fields=sys_id,number,state,correlation_id,cmdb_ci,business_service,service_offering,assignment_group,assigned_to,u_environment,priority&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/incident?sysparm_query=correlation_id=__DISPLAY_ID__%5EORDERBYDESCsys_created_on&sysparm_fields=sys_id,number,state,correlation_id&sysparm_limit=5" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" -H "Content-Type: application/json" -X POST "https://silvastg.service-now.com/api/now/v2/table/incident?sysparm_input_display_value=true&sysparm_display_value=true&sysparm_exclude_reference_link=true" -d '{"short_description":"[DYNATRACE JAPAN] API TEST - please ignore","description":"API test","contact_type":"Event","impact":"4","urgency":"4","correlation_id":"API-TEST-001","cmdb_ci":"ts12.hk.intraxa","assignment_group":"InfraSupport_Dist-WindowsHK_L2_ASIA","u_environment":"Integration / Test"}' | jq '.result | {sys_id, number, cmdb_ci, business_service, service_offering, assignment_group, u_environment}'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" -H "Content-Type: application/json" -X PATCH "https://silvastg.service-now.com/api/now/v2/table/incident/__INCIDENT_SYS_ID__" -d '{"state":"6","close_code":"Solved (Permanently)","close_notes":"API test resolved"}' | jq '.result | {number, state, close_code}'
open "https://silvastg.service-now.com/sys_dictionary_list.do?sysparm_query=name=service_offering"
open "https://silvastg.service-now.com/incident.do?sysparm_query=number=INC30339746"
brew install jq
