open "https://app.diagrams.net"
open "https://excalidraw.com"
open "https://mermaid.live"
open "https://www.lucidchart.com"
open "https://miro.com"
open "https://www.figma.com/figjam/"
open "https://icepanel.io"
open "https://www.cloudcraft.co"
open "https://structurizr.com"
open "https://www.plantuml.com/plantuml/uml"
open "https://d2lang.com"
open "https://whimsical.com"
open "https://github.com/jgraph/drawio-desktop"
echo "Recommended for ARB AS-IS/TO-BE/HLD: diagrams.net → export PNG → paste into PowerPoint"
echo "Recommended for Git docs: mermaid.live or Mermaid in Markdown"
echo "Check company policy before uploading confidential diagrams to public SaaS"
echo "git add /Users/k/Codes/Pra/P1GithubActions/P1Gactions/app/Adocs/2026-08-31/12-architecture-diagram-drawing-tools"
echo "git -C /Users/k/Codes/Pra/P1GithubActions/P1Gactions commit -m \"Add architecture diagram drawing tools guide\""
echo "git -C /Users/k/Codes/Pra/P1GithubActions/P1Gactions push"
