echo "API catalog: /Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/25-four-tools-api-catalog/25-four-tools-api-catalog.md"
echo "Dynatrace: /api/v2/problems metrics entities events ..."
echo "ServiceNow: /api/now/v2/table/{table}"
echo "PagerDuty: events.pagerduty.com/v2/enqueue + api.pagerduty.com"
echo "Splunk: :8089/services/search/... + HEC /services/collector"
ls "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/25-four-tools-api-catalog"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" add "app/Adocs/2026-09-17/25-four-tools-api-catalog"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" status --short "app/Adocs/2026-09-17/25-four-tools-api-catalog"
echo "Do not commit/push unless user asks"
