diff "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-28/6-sep24-open-close-enrich-only/1-open-silva-http-and-pagerduty.workflow.yaml" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-28/7-open-close-example-testing-group/1-open-silva-http-and-pagerduty.workflow.yaml"
diff "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-28/6-sep24-open-close-enrich-only/2-close-silva-http-and-pagerduty.workflow.yaml" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-28/7-open-close-example-testing-group/2-close-silva-http-and-pagerduty.workflow.yaml"
rg -n "TEST_ASSIGNMENT_GROUP|__[A-Z0-9_]+__" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-28/7-open-close-example-testing-group/"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' "https://silvastg.service-now.com/api/now/v2/table/sys_user_group?sysparm_query=name=testing%203122^active=true&sysparm_fields=name,sys_id,active"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci_service?sysparm_query=name=Third%20Party%20Services%20Monitoring%20Application&sysparm_fields=name,sys_id"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' "https://silvastg.service-now.com/api/now/v2/table/sys_choice?sysparm_query=name=incident^elementINimpact,urgency^inactive=false&sysparm_fields=element,label,value"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' "https://silvastg.service-now.com/api/now/v2/table/incident?sysparm_query=number=INC30339566&sysparm_display_value=true&sysparm_fields=number,contact_type,company,u_environment,business_service,service_offering,cmdb_ci,category,subcategory,impact,urgency,priority,assignment_group"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' "https://silvastg.service-now.com/api/now/v2/table/incident?sysparm_query=assignment_group.name=testing%203122^ORDERBYDESCsys_created_on&sysparm_limit=5&sysparm_display_value=true&sysparm_fields=number,short_description,assignment_group,priority,correlation_id"
cd /Users/k/Codes/Pra/P1GithubActions/P1Gactions && git add app/Adocs/2026-09-28/7-open-close-example-testing-group
cd /Users/k/Codes/Pra/P1GithubActions/P1Gactions && git commit -m "docs: align SILVA open/close workflows to example ticket, testing 3122 group"
cd /Users/k/Codes/Pra/P1GithubActions/P1Gactions && git push
