curl -s -I -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/svc_ci_assoc?sysparm_limit=1" | grep -i x-total-count
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/svc_ci_assoc?sysparm_query=ORDERBYci_id.name&sysparm_fields=ci_id.name,ci_id.fqdn,ci_id.sys_class_name,ci_id.install_status,ci_id.support_group,service_id.name,service_id.support_group,service_id.operational_status&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=10000&sysparm_offset=0" | jq -r '["host","host_fqdn","host_class","host_status","host_support_group","business_service","service_support_group","service_status"], (.result[] | [.["ci_id.name"],.["ci_id.fqdn"],.["ci_id.sys_class_name"],.["ci_id.install_status"],.["ci_id.support_group"],.["service_id.name"],.["service_id.support_group"],.["service_id.operational_status"]]) | @csv' > silva_ci_service_0.csv
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/svc_ci_assoc?sysparm_query=ORDERBYci_id.name&sysparm_fields=ci_id.name,ci_id.fqdn,ci_id.sys_class_name,ci_id.install_status,ci_id.support_group,service_id.name,service_id.support_group,service_id.operational_status&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=10000&sysparm_offset=10000" | jq -r '.result[] | [.["ci_id.name"],.["ci_id.fqdn"],.["ci_id.sys_class_name"],.["ci_id.install_status"],.["ci_id.support_group"],.["service_id.name"],.["service_id.support_group"],.["service_id.operational_status"]] | @csv' > silva_ci_service_1.csv
cat silva_ci_service_0.csv silva_ci_service_1.csv > silva_ci_service.csv
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/service_offering?sysparm_query=ORDERBYname&sysparm_fields=name,parent,u_environment,support_group,company&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=10000" | jq -r '["offering","business_service","offering_environment","offering_support_group","company"], (.result[] | [.name,.parent,.u_environment,.support_group,.company]) | @csv' > silva_service_offerings.csv
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/cmdb_rel_ci?sysparm_query=parent.sys_class_nameINSTANCEOFcmdb_ci_service&sysparm_fields=child.name,child.fqdn,child.sys_class_name,child.install_status,child.support_group,parent.name,parent.support_group,parent.operational_status&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=10000&sysparm_offset=0" | jq -r '["host","host_fqdn","host_class","host_status","host_support_group","business_service","service_support_group","service_status"], (.result[] | [.["child.name"],.["child.fqdn"],.["child.sys_class_name"],.["child.install_status"],.["child.support_group"],.["parent.name"],.["parent.support_group"],.["parent.operational_status"]]) | @csv' > silva_ci_service_rel.csv
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_user_group?sysparm_query=active=true%5EORDERBYname&sysparm_fields=name,manager,email,parent&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=10000" | jq -r '["group","manager","email","parent"], (.result[] | [.name,.manager,.email,.parent]) | @csv' > silva_assignment_groups.csv
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_choice?sysparm_query=name=incident%5Eelement=u_environment%5Einactive=false&sysparm_fields=label,value&sysparm_limit=100" | jq -r '["label","value"], (.result[] | [.label,.value]) | @csv' > silva_environments.csv
python3 "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-28/30-export-whole-silva-mapping-table/30-join-silva-tables.py" silva_ci_service.csv silva_service_offerings.csv silva_whole_table.csv
open "https://silvastg.service-now.com/svc_ci_assoc_list.do"
open "https://silvastg.service-now.com/service_offering_list.do"
open "https://silvastg.service-now.com/svc_ci_assoc_list.do?CSV"
open "https://silvastg.service-now.com/service_offering_list.do?CSV"
brew install jq
