curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/table/sys_documentation" --data-urlencode "sysparm_query=nameINincident,task^language=en^labelINSummary,Reported on,User Location,Department,SO Display Name,Hot Ticket,First Contact Resolvable,Regulation Type,Actual Start Date,Open Group,Incident Substate,Customer Callback,Customer Appointment,Owner Group,Effort,Vendor / Interface,External Ticket Number,Approved,On Behalf Of,Environment" --data-urlencode "sysparm_fields=name,element,label" --data-urlencode "sysparm_limit=200"
curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/table/sys_dictionary" --data-urlencode "sysparm_query=nameINincident,task^elementINdescription,opened_at,u_user_location,u_department,u_so_display_name,u_hot_ticket,u_first_contact_resolvable,u_regulation_type,u_actual_start_date,u_open_group,u_incident_substate,u_customer_callback,u_customer_appointment,u_owner_group,u_effort,u_vendor_interface,u_external_ticket_number,u_approved,u_on_behalf_of,u_environment" --data-urlencode "sysparm_fields=name,element,column_label,internal_type,reference,read_only,mandatory" --data-urlencode "sysparm_limit=200"
curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/table/incident" --data-urlencode "sysparm_query=number=INC30340215" --data-urlencode "sysparm_display_value=all" --data-urlencode "sysparm_fields=number,caller_id,u_on_behalf_of,contact_type,company,location,u_user_location,u_department,u_environment,business_service,service_offering,u_so_display_name,cmdb_ci,category,subcategory,u_hot_ticket,u_first_contact_resolvable,u_regulation_type,short_description,description,opened_at,u_reported_on,u_actual_start_date,opened_by,u_open_group,incident_state,state,u_incident_substate,u_customer_callback,u_customer_appointment,priority,impact,urgency,u_owner_group,assignment_group,assigned_to,u_effort,due_date,u_vendor_interface,u_external_ticket_number,parent_incident,u_approved,correlation_id"
curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/table/incident" --data-urlencode "sysparm_query=number=INC30340215" --data-urlencode "sysparm_display_value=all" | jq -r '.result[0] | keys[]'
curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/table/sys_dictionary" --data-urlencode "sysparm_query=nameINincident,task^element=u_hot_ticket" --data-urlencode "sysparm_fields=name,element,column_label,internal_type"
curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/table/sys_dictionary" --data-urlencode "sysparm_query=nameINincident,task^column_labelLIKEHot" --data-urlencode "sysparm_fields=name,element,column_label,internal_type"
curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/table/sys_choice" --data-urlencode "sysparm_query=nameINincident,task^elementINimpact,urgency,u_environment,contact_type,category,subcategory,incident_state,u_incident_substate,u_regulation_type^inactive=false" --data-urlencode "sysparm_fields=element,value,label,dependent_value" --data-urlencode "sysparm_limit=500"
open "https://silvastg.service-now.com/sys_dictionary_list.do?sysparm_query=nameINincident,task%5EelementSTARTSWITHu_"
open "https://silvastg.service-now.com/sys_documentation_list.do?sysparm_query=nameINincident,task%5Elanguage=en"
