# Seq 17 — Column L host group IDs — paste into Dynatrace Logs and Events → Advanced mode
# Inventory — log count per host group (column L IDs, 53 groups)
fetch logs, from: now()-24h | filter in(dt.host_group.id, { "C_ALJ_BU_ADL_A_AgencyFeeAuto-Send_E_PRD", "C_ALJ_BU_ADL_A_Backup_E_DR", "C_ALJ_BU_ADL_A_CoreFileServer_E_PRD", "C_ALJ_BU_ADL_A_CoreStor_E_PRD", "C_ALJ_BU_ADL_A_DataExtractionTool_E_PRD", "C_ALJ_BU_ADL_A_DocUpload_E_PRD", "C_ALJ_BU_ADL_A_DomainController_E_PRD", "C_ALJ_BU_ADL_A_EventLogManagement_E_PRD", "C_ALJ_BU_ADL_A_GitRedmine_E_OA", "C_ALJ_BU_ADL_A_Hulft_E_PRD", "C_ALJ_BU_ADL_A_ILMT_E_PRD", "C_ALJ_BU_ADL_A_InformationManagement_E_PRD", "C_ALJ_BU_ADL_A_JP1-AJS3_E_DR", "C_ALJ_BU_ADL_A_MQ-PDF-Mail_E_PRD", "C_ALJ_BU_ADL_A_ORA-WFA_E_PRD", "C_ALJ_BU_ADL_A_OracleDB_E_PRD", "C_ALJ_BU_ADL_A_Payment_E_PRD", "C_ALJ_BU_ADL_A_Proxy_E_PRD", "C_ALJ_BU_ADL_A_Rism_E_PRD", "C_ALJ_BU_ADL_A_SMTP_E_PRD", "C_ALJ_BU_ADL_A_Satellite_E_OA", "C_ALJ_BU_ADL_A_Terminal_E_OA", "C_ALJ_BU_ADL_A_WSUS_E_PRD", "C_ALJ_BU_ADL_A_Web-AP-Server_E_PRD", "C_ALJ_BU_ADL_A_Web_E_PRD", "C_ALJ_BU_AG-PORTAL-CLOUD_A_AGPORTALAPI_E_PRD_T_PROXY", "C_ALJ_BU_CLAIMS-RECEPTION-A_ICM_E_PRD_T_DOCHUB", "C_ALJ_BU_DAMPOSHIN_A_BCCALC_E_PRD_T_DB", "C_ALJ_BU_DAMPOSHIN_A_CANWEB_E_PRD_T_DB", "C_ALJ_BU_DATAENGLF_A_CUSTMDMGM_E_PRD_T_APP", "C_ALJ_BU_DATAENGLF_A_FILENETFN_E_PRD_T_APP", "C_ALJ_BU_DATA_A_TAXRPRTMG_E_PRD_T_APP", "C_ALJ_BU_DATA_A_TAXRPRTMG_E_PRD_T_DB", "C_ALJ_BU_DATADA_A_BICCIPSIM_E_PRD_T_DB", "C_ALJ_BU_GIC-TOUCHPOINT_A_CANWEB_E_PRD_T_PROXY", "C_ALJ_BU_HR_A_PSOFTHRMG_E_PRD_T_APP", "C_ALJ_BU_MIDDLEWARE-A_SITEMINDER_E_PRD_T_RESERVEPROXY", "C_ALJ_BU_MIDDLEWARE-SHARED-PRODUCT_A_ETL_E_PRD_T_APP", "C_ALJ_BU_MIDDLEWARE-SHARED-PRODUCT_A_HATS_E_PRD_T_APP", "C_ALJ_BU_MIDDLEWARE_A_CUSTMDMGM_E_PRD_T_APP", "C_ALJ_BU_MIDDLEWARE_A_DFS_E_PRD_T_APP", "C_ALJ_BU_MIDDLEWARE_A_EIP_E_PRD_T_APP", "C_ALJ_BU_MIDDLEWARE_A_EIP_E_PRD_T_DB", "C_ALJ_BU_MIDDLEWARE_A_ETLPCBTCH_E_PRD_T_APP", "C_ALJ_BU_MIDDLEWARE_A_FTPSSBTB_E_PRD_T_APP", "C_ALJ_BU_MIDDLEWARE_A_HULFT_E_PRD_T_APP", "C_ALJ_BU_MIDDLEWARE_A_IWFM_E_PRD_T_APP", "C_ALJ_BU_MIDDLEWARE_A_MQ_E_PRD_T_APP", "C_ALJ_BU_MIDDLEWARE_A_UDM_E_PRD_T_APP", "C_ALJ_BU_MSP_A_OUD_E_PRD_T_OUD", "C_ALJ_BU_NEW-BUSINESS_A_NBWF_E_PRD_T_BATCH", "C_ALJ_BU_PLATFARCH_A_ETLPCBTCH_E_PRD_T_DB", "C_ALJ_BU_PLATFARCH_A_FILENETFN_E_PRD_T_DB", "C_ALJ_BU_PLATFARCH_A_LOADRUNNR_E_PRD_T_APP" }) | summarize log_count = count(), by: { dt.host_group.id } | sort log_count desc
# Per-host verify — Customer MDM CEAA006B (column L group)
fetch logs, from: now()-24h | filter host.name == "CEAA006B.PRPRIVMGMT.intra" | filter matchesValue(dt.host_group.id, "C_ALJ_BU_DATAENGLF_A_CUSTMDMGM_E_PRD_T_APP") | summarize log_count = count(), by: { dt.host_group.id, host.name }
# Per-host verify — People Soft HR CEAA0059 (column L group)
fetch logs, from: now()-24h | filter host.name == "CEAA0059.PRPRIVMGMT.intra" | filter matchesValue(dt.host_group.id, "C_ALJ_BU_HR_A_PSOFTHRMG_E_PRD_T_APP") | summarize log_count = count(), by: { dt.host_group.id, host.name }
# Master PII + HATS — paste full block from 17-dql-hostgroup-column-l-update.md (same ID list as inventory)
# Excel — copy column L values into column B (paste values only)
# wc -l unique-col-l.sh (local count check)
wc -l "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-08-28/17-dql-hostgroup-column-l-update/unique-col-l.sh"
