echo "SNOW functions: /Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/28-snow-common-functions-how-to/28-snow-common-functions-how-to.md"
echo "Create Assign Comment Search Resolve — UI or snow-* actions"
ls "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/28-snow-common-functions-how-to"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" add "app/Adocs/2026-09-17/28-snow-common-functions-how-to"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" status --short "app/Adocs/2026-09-17/28-snow-common-functions-how-to"
echo "Do not commit/push unless user asks"
