grep -nE "getProblem|getRows\(|fetch\(|getJson\(" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-30/9-v6-full-open-silva-pagerduty/9-v6-full-open-silva-pagerduty.workflow.yaml"
grep -nE "getProblem|fetch\(|getJson\(" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-30/11-v6-close-silva-pagerduty/11-v6-close-silva-pagerduty.workflow.yaml"
grep -nE "ex.result\(" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-30/9-v6-full-open-silva-pagerduty/9-v6-full-open-silva-pagerduty.workflow.yaml"
grep -nE "ex.result\(" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-30/11-v6-close-silva-pagerduty/11-v6-close-silva-pagerduty.workflow.yaml"
curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/v2/table/sys_user_group" --data-urlencode "sysparm_query=name=Database_AXAJP^active=true" --data-urlencode "sysparm_fields=sys_id,name,company" --data-urlencode "sysparm_display_value=all"
curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci_service" --data-urlencode "sysparm_query=assignment_group.nameLIKEDatabase_AXAJP" --data-urlencode "sysparm_fields=sys_id,name,assignment_group,support_group" --data-urlencode "sysparm_limit=5"
curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/v2/table/service_offering" --data-urlencode "sysparm_query=parent.name=QA Platforms^nameSTARTSWITHQA Platforms - AXA GROUP OPERATIONS" --data-urlencode "sysparm_fields=sys_id,name,u_environment"
curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/v2/table/incident" --data-urlencode "sysparm_query=correlation_id=<display_id>^active=true" --data-urlencode "sysparm_fields=sys_id,number,state,active"
curl -s -u 'Tech_DynatraceJP_WS:<password>' -G "https://silvastg.service-now.com/api/now/v2/table/incident" --data-urlencode "sysparm_query=number=INC30340215" --data-urlencode "sysparm_fields=state,close_code,impact,urgency,u_environment,u_on_behalf_of"
curl -s -X POST "https://events.pagerduty.com/v2/enqueue" -H "Content-Type: application/json" -d '{"routing_key":"<ROUTING_KEY>","event_action":"trigger","dedup_key":"dt-problem-TEST-1","payload":{"summary":"test from curl","source":"manual","severity":"info"}}'
curl -s -X POST "https://events.pagerduty.com/v2/enqueue" -H "Content-Type: application/json" -d '{"routing_key":"<ROUTING_KEY>","event_action":"resolve","dedup_key":"dt-problem-TEST-1"}'
mkdir -p "/Users/k/Work/AIProjects/Files/2026-09-30"
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-30/13-open-close-workflow-task-api-summary" "/Users/k/Work/AIProjects/Files/2026-09-30/"
