curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/sys_user" -H 'Accept: application/json' --data-urlencode "sysparm_query=sys_id=8ddef691fb34cf547b0dfe7b4eefdcbc" --data-urlencode "sysparm_fields=sys_id,user_name,name,active" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/sys_user_group" -H 'Accept: application/json' --data-urlencode "sysparm_query=sys_id=5223d8c61b8f3c54688064e4604bcb12" --data-urlencode "sysparm_fields=sys_id,name,active" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci_service" -H 'Accept: application/json' --data-urlencode "sysparm_query=sys_id=03bd24ce1b477c54688064e4604bcbd4" --data-urlencode "sysparm_fields=sys_id,name,sys_class_name,operational_status" --data-urlencode "sysparm_display_value=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/service_offering" -H 'Accept: application/json' --data-urlencode "sysparm_query=sys_id=3d62b88e1b877c54688064e4604bcba5" --data-urlencode "sysparm_fields=sys_id,name,parent,operational_status,support_group" --data-urlencode "sysparm_display_value=all" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/service_offering" -H 'Accept: application/json' --data-urlencode "sysparm_query=parent=03bd24ce1b477c54688064e4604bcbd4" --data-urlencode "sysparm_fields=sys_id,name,operational_status" --data-urlencode "sysparm_display_value=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci" -H 'Accept: application/json' --data-urlencode "sysparm_query=sys_id=485b4cee1b4d811050b89863b24bcbeb" --data-urlencode "sysparm_fields=sys_id,name,fqdn,sys_class_name,install_status,operational_status" --data-urlencode "sysparm_display_value=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/core_company" -H 'Accept: application/json' --data-urlencode "sysparm_query=sys_id=3e731d56dba4f6c8a476f9f51d96193f" --data-urlencode "sysparm_fields=sys_id,name" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/sys_choice" -H 'Accept: application/json' --data-urlencode "sysparm_query=name=incident^elementINimpact,urgency,contact_type,category,subcategory^inactive=false" --data-urlencode "sysparm_fields=element,value,label" | jq -r '.result[] | "\(.element)\t\(.value)\t\(.label)"'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/incident" -H 'Accept: application/json' --data-urlencode "sysparm_query=correlation_id=P-260916434^active=true" --data-urlencode "sysparm_fields=number,state,sys_created_on" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/incident" -H 'Accept: application/json' --data-urlencode "sysparm_query=correlation_id=P-260916434" --data-urlencode "sysparm_fields=number,caller_id,u_on_behalf_of,assignment_group,u_business_service,cmdb_ci,u_configuration_item,company,impact,urgency,priority,u_environment,contact_type,category,subcategory,correlation_id,short_description" --data-urlencode "sysparm_display_value=all" | jq '.result'
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/21-silva-verify-checklist" "/Users/k/Work/AIProjects/Files/2026-10-01/"
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/21-silva-verify-checklist" "/Users/k/Codes/Pra/P1GithubActions/P1Gactions/app/Adocs/2026-10-01/"
