open "https://support.pagerduty.com/main/docs/event-orchestration"
open "https://support.pagerduty.com/main/docs/alert-grouping"
open "https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTgw-send-an-alert-event"
open "https://support.pagerduty.com/main/docs/change-events"
open "https://docs.dynatrace.com/docs/analyze-explore-automate/notifications-and-alerting/problem-notifications/pagerduty-integration"
open "https://REPLACE_ME.pagerduty.com/event-orchestration"
echo "0) Create poc-eo-default db infra app Services + test EP (page only you) + Global EO"
echo "1-4) Enable Intelligent/content-by-host grouping on infra/app; prove one incident storms"
echo "5-7) EO Route Oracle->db Java->app Linux->infra; 10) catch-all default last"
echo "8) Pause 5m for flapping; resolve inside window = no page"
echo "9) Change Event + pause/suppress deploy blip; Dynatrace resolve self-closes"
echo "Never use prod Integration Keys for this POC"
echo "git add /Users/k/Codes/Pra/P1GithubActions/P1Gactions/app/Adocs/2026-08-31/7-pagerduty-event-orchestration-poc"
echo "git -C /Users/k/Codes/Pra/P1GithubActions/P1Gactions commit -m \"Add Event Orchestration ten-scenario POC Adocs\""
echo "git -C /Users/k/Codes/Pra/P1GithubActions/P1Gactions push"
