curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci?sysparm_query=name=ts12.hk.intraxa%5EORname=ts12%5EORfqdn=ts12.hk.intraxa&sysparm_fields=sys_id,name,fqdn,sys_class_name,install_status,support_group&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/svc_ci_assoc?sysparm_query=ci_id.name=ts12.hk.intraxa%5EORci_id.name=ts12&sysparm_fields=service_id,ci_id&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci_service?sysparm_query=name=Third%20Party%20Services%20Monitoring%20Application&sysparm_fields=sys_id,name,sys_class_name,operational_status,support_group,managed_by_group&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/service_offering?sysparm_query=parent.name=Third%20Party%20Services%20Monitoring%20Application&sysparm_fields=name,u_environment,support_group&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_user_group?sysparm_query=name=InfraSupport_Dist-WindowsHK_L2_ASIA&sysparm_fields=name,sys_id,active,manager&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_choice?sysparm_query=name=incident%5Eelement=u_environment%5Einactive=false&sysparm_fields=label,value&sysparm_limit=100" | jq -r '.result[] | [.label,.value] | @tsv'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/incident?sysparm_query=number=INC30339746&sysparm_fields=number,correlation_id,cmdb_ci,business_service,service_offering,assignment_group,u_environment&sysparm_display_value=true&sysparm_exclude_reference_link=true" | jq '.result'
open "https://silvastg.service-now.com/cmdb_ci_server_list.do?sysparm_query=nameLIKEts12"
open "https://silvastg.service-now.com/svc_ci_assoc_list.do?sysparm_query=ci_id.nameLIKEts12"
