curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/stats/sys_user_group?sysparm_count=true&sysparm_query=active=true"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/stats/cmdb_ci_service?sysparm_count=true"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/stats/service_offering?sysparm_count=true"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_user_group?sysparm_query=active=true%5EORDERBYname&sysparm_fields=name,sys_id,type,manager,email,parent&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=10000" | jq -r '.result[] | [.name,.sys_id,.type,.manager,.email,.parent] | @csv' > silva_assignment_groups.csv
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci_service?sysparm_query=ORDERBYname&sysparm_fields=name,sys_id,operational_status,support_group,assignment_group,managed_by_group,owned_by&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=10000" | jq -r '.result[] | [.name,.sys_id,.operational_status,.support_group,.assignment_group,.managed_by_group,.owned_by] | @csv' > silva_business_services.csv
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/service_offering?sysparm_query=ORDERBYname&sysparm_fields=name,sys_id,parent,u_environment,support_group,assignment_group,company&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_limit=10000" | jq -r '.result[] | [.name,.sys_id,.parent,.u_environment,.support_group,.assignment_group,.company] | @csv' > silva_service_offerings.csv
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/sys_user_group?sysparm_query=active=true%5EnameLIKEAXAJP&sysparm_fields=name,sys_id&sysparm_limit=200"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/svc_ci_assoc?sysparm_query=ci_id.name=__HOST_NAME__&sysparm_fields=service_id,ci_id&sysparm_display_value=true&sysparm_exclude_reference_link=true"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/cmdb_rel_ci?sysparm_query=child.name=__HOST_NAME__%5Eparent.sys_class_name=cmdb_ci_service&sysparm_fields=parent,child,type&sysparm_display_value=true&sysparm_exclude_reference_link=true"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci_server?sysparm_query=name=__HOST_NAME__&sysparm_fields=name,sys_id,support_group,assignment_group&sysparm_display_value=true&sysparm_exclude_reference_link=true"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci_service?sysparm_query=ORDERBYname&sysparm_fields=name,sys_id&sysparm_limit=5000&sysparm_offset=5000"
open "https://silvastg.service-now.com/sys_user_group_list.do?CSV&sysparm_query=active=true"
open "https://silvastg.service-now.com/cmdb_ci_service_list.do?CSV"
open "https://silvastg.service-now.com/service_offering_list.do?CSV"
open "https://silvastg.service-now.com/svc_ci_assoc_list.do?CSV"
brew install jq
