apiVersion: v1
kind: Service
metadata:
  name: p1gactions
  labels:
    app: p1gactions
spec:
  type: NodePort
  selector:
    app: p1gactions
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
