SNOW_USER='Tech_DynatraceJP_WS'
SNOW_PASS='<password>'
SNOW='https://silvastg.service-now.com'
curl -s -G -u "$SNOW_USER:$SNOW_PASS" "$SNOW/api/now/v2/table/cmdb_ci_service" --data-urlencode 'sysparm_query=assignment_group.nameLIKEDatabase_AXAJP' --data-urlencode 'sysparm_fields=sys_id,name,number,assignment_group,support_group,company' --data-urlencode 'sysparm_display_value=true' --data-urlencode 'sysparm_limit=20' | jq '.result[] | {name, number, sys_id, company}'
curl -s -G -u "$SNOW_USER:$SNOW_PASS" "$SNOW/api/now/v2/table/cmdb_ci_service" --data-urlencode 'sysparm_query=support_group.nameLIKEDatabase_AXAJP' --data-urlencode 'sysparm_fields=sys_id,name,number,company' --data-urlencode 'sysparm_display_value=true' --data-urlencode 'sysparm_limit=20' | jq
curl -s -G -u "$SNOW_USER:$SNOW_PASS" "$SNOW/api/now/v2/table/cmdb_ci_service" --data-urlencode 'sysparm_query=assignment_group.nameLIKEDatabase_AXAJP^nameLIKEIntegration / Test' --data-urlencode 'sysparm_fields=sys_id,name,number,company' --data-urlencode 'sysparm_display_value=true' | jq
curl -s -G -u "$SNOW_USER:$SNOW_PASS" "$SNOW/api/now/v2/table/cmdb_ci_service" --data-urlencode 'sysparm_query=nameLIKEALJ' --data-urlencode 'sysparm_fields=sys_id,name,number,company' --data-urlencode 'sysparm_display_value=true' --data-urlencode 'sysparm_limit=20' | jq
curl -s -G -u "$SNOW_USER:$SNOW_PASS" "$SNOW/api/now/v2/table/service_offering" --data-urlencode 'sysparm_query=assignment_group.nameLIKEDatabase_AXAJP' --data-urlencode 'sysparm_fields=sys_id,name,u_environment,parent' --data-urlencode 'sysparm_display_value=true' --data-urlencode 'sysparm_limit=20' | jq
curl -s -G -u "$SNOW_USER:$SNOW_PASS" "$SNOW/api/now/v2/table/service_offering" --data-urlencode 'sysparm_query=parent.name=Informatica - AXA DIRECT JAPAN - Integration / Test - Gold' --data-urlencode 'sysparm_fields=sys_id,name,u_environment' --data-urlencode 'sysparm_display_value=true' | jq
curl -s -G -u "$SNOW_USER:$SNOW_PASS" "$SNOW/api/now/v2/table/sys_user_group" --data-urlencode 'sysparm_query=name=Database_AXAJP' --data-urlencode 'sysparm_fields=sys_id,name,company' --data-urlencode 'sysparm_display_value=true' | jq
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-30/3-extract-v4-business-service-and-group" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-30/7-first-answer-fallback-by-group" "/Users/k/Work/AIProjects/Files/2026-09-30/"
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-30/3-extract-v4-business-service-and-group" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-30/7-first-answer-fallback-by-group" "/Users/k/Codes/Pra/P1GithubActions/P1Gactions/app/Adocs/2026-09-30/"
# Do NOT push app/Adocs: the workflow YAML contains the SNOW password
