export DT="https://wuh86725.apps.dynatrace.com"
export DTTOKEN="__DT_PLATFORM_TOKEN__"
export SN="https://silvastg.service-now.com"
export SNAUTH='Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}'
curl -s -H "Authorization: Bearer $DTTOKEN" "$DT/platform/automation/v1/workflows?search=AGO"
curl -s -H "Authorization: Bearer $DTTOKEN" "$DT/platform/automation/v1/executions?workflow=<WORKFLOW_ID>&limit=10"
curl -s -H "Authorization: Bearer $DTTOKEN" "$DT/platform/automation/v1/executions/<EXECUTION_ID>/tasks"
curl -s -H "Authorization: Bearer $DTTOKEN" "$DT/platform/automation/v1/executions/<EXECUTION_ID>/tasks/resolve-snow-values/result"
curl -s -H "Authorization: Bearer $DTTOKEN" "$DT/platform/automation/v1/executions/<EXECUTION_ID>/tasks/post-silva-incident/log"
curl -s -H "Authorization: Bearer $DTTOKEN" "$DT/platform/automation/v1/executions/<EXECUTION_ID>/tasks/close-silva-incident/result"
curl -s -u "$SNAUTH" -H "Accept: application/json" "$SN/api/now/v2/table/incident?sysparm_query=number%3DINC30341416&sysparm_fields=sys_id,number,state,incident_state,correlation_id"
curl -s -u "$SNAUTH" -H "Accept: application/json" "$SN/api/now/v2/table/sys_audit?sysparm_query=tablename%3Dincident%5Edocumentkey%3D<INCIDENT_SYS_ID>%5EORDERBYsys_created_on&sysparm_fields=sys_created_on,user,fieldname,oldvalue,newvalue&sysparm_limit=200"
curl -s -u "$SNAUTH" -H "Accept: application/json" "$SN/api/now/v2/table/sys_journal_field?sysparm_query=element_id%3D<INCIDENT_SYS_ID>%5EORDERBYsys_created_on&sysparm_fields=sys_created_on,sys_created_by,element,value&sysparm_limit=50"
curl -s -H "Authorization: Token token=__PD_REST_API_KEY__" -H "Accept: application/vnd.pagerduty+json;version=2" "https://api.pagerduty.com/incidents?incident_key=dt-problem-P-261090"
curl -s -H "Authorization: Token token=__PD_REST_API_KEY__" -H "Accept: application/vnd.pagerduty+json;version=2" "https://api.pagerduty.com/incidents/<PD_INCIDENT_ID>/log_entries"
rg -n "^\s+(async )?function |^\s+const \w+ = (\(|async|\w+ =>)" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/36-standard-flow-preview-then-post/36-standard-flow-preview-then-post.workflow.yaml"
rg -n "^\s+(async )?function |^\s+const \w+ = (\(|async|\w+ =>)" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/45-close-direct-v5-trigger-closed/45-close-direct-v5-trigger-closed.workflow.yaml"
rg -n "fetch\(|getRows\(|patch\(|getProblem" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/36-standard-flow-preview-then-post/36-standard-flow-preview-then-post.workflow.yaml" "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/45-close-direct-v5-trigger-closed/45-close-direct-v5-trigger-closed.workflow.yaml"
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/51-workflows-functions-api-traces" "/Users/k/Work/AIProjects/Files/2026-10-01/"
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/51-workflows-functions-api-traces" "/Users/k/Codes/Pra/P1GithubActions/P1Gactions/app/Adocs/2026-10-01/"
cd /Users/k/Codes/Pra/P1GithubActions/P1Gactions && git add app/Adocs/2026-10-01/51-workflows-functions-api-traces/*.md app/Adocs/2026-10-01/51-workflows-functions-api-traces/*.txt
cd /Users/k/Codes/Pra/P1GithubActions/P1Gactions && git commit -m "docs: workflow functions and api traces"
cd /Users/k/Codes/Pra/P1GithubActions/P1Gactions && git push
