curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/sys_user_group" -H 'Accept: application/json' --data-urlencode "sysparm_query=name=Database_AXAJP^active=true" --data-urlencode "sysparm_fields=sys_id,name,active,company" --data-urlencode "sysparm_display_value=all" --data-urlencode "sysparm_limit=1" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci" -H 'Accept: application/json' --data-urlencode "sysparm_query=name=deaa310b^ORfqdn=deaa310b.prprivmgmt.intraxa^ORnameSTARTSWITHdeaa310b." --data-urlencode "sysparm_fields=sys_id,name,fqdn,sys_class_name,install_status,support_group,business_service,service" --data-urlencode "sysparm_display_value=all" --data-urlencode "sysparm_limit=10" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/svc_ci_assoc" -H 'Accept: application/json' --data-urlencode "sysparm_query=ci_id=485b4cee1b4d811050b89863b24bcbeb" --data-urlencode "sysparm_fields=service_id" --data-urlencode "sysparm_display_value=all" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/cmdb_rel_ci" -H 'Accept: application/json' --data-urlencode "sysparm_query=child=485b4cee1b4d811050b89863b24bcbeb" --data-urlencode "sysparm_fields=parent,parent.sys_class_name,type" --data-urlencode "sysparm_display_value=all" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci_service" -H 'Accept: application/json' --data-urlencode "sysparm_query=sys_id=03bd24ce1b477c54688064e4604bcbd4" --data-urlencode "sysparm_fields=sys_id,name,sys_class_name,assignment_group,support_group,company,parent" --data-urlencode "sysparm_display_value=all" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/service_offering" -H 'Accept: application/json' --data-urlencode "sysparm_query=parent=03bd24ce1b477c54688064e4604bcbd4" --data-urlencode "sysparm_fields=sys_id,name,u_environment,operational_status,parent" --data-urlencode "sysparm_display_value=all" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/incident" -H 'Accept: application/json' --data-urlencode "sysparm_query=correlation_id=P-260916434^active=true" --data-urlencode "sysparm_fields=number,state,assignment_group" --data-urlencode "sysparm_display_value=true" --data-urlencode "sysparm_limit=1" | jq '.result'
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/24-workflow-flow-apis-explained" "/Users/k/Work/AIProjects/Files/2026-10-01/"
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/24-workflow-flow-apis-explained" "/Users/k/Codes/Pra/P1GithubActions/P1Gactions/app/Adocs/2026-10-01/"
