curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/cmdb_ci" -H 'Accept: application/json' --data-urlencode "sysparm_query=sys_id=1dfdcf8adb8dfa40251af9971d961941" --data-urlencode "sysparm_fields=sys_id,name,sys_class_name,operational_status,support_group,company" --data-urlencode "sysparm_display_value=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/incident" -H 'Accept: application/json' --data-urlencode "sysparm_query=u_configuration_item=1dfdcf8adb8dfa40251af9971d961941^cmdb_ciISNOTEMPTY^ORDERBYDESCsys_created_on" --data-urlencode "sysparm_fields=number,cmdb_ci,u_business_service,assignment_group,sys_created_on" --data-urlencode "sysparm_display_value=true" --data-urlencode "sysparm_limit=20" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/incident" -H 'Accept: application/json' --data-urlencode "sysparm_query=u_configuration_item=1dfdcf8adb8dfa40251af9971d961941^cmdb_ciISNOTEMPTY" --data-urlencode "sysparm_fields=cmdb_ci" --data-urlencode "sysparm_limit=20" | jq -r '.result[].cmdb_ci.value' | sort | uniq -c | sort -rn
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/service_offering" -H 'Accept: application/json' --data-urlencode "sysparm_query=sys_id=cfbf255f1b03b49416deb166464bcb4b" --data-urlencode "sysparm_fields=sys_id,name,parent,u_environment,operational_status,assignment_group,support_group,company" --data-urlencode "sysparm_display_value=all" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/sys_user_group" -H 'Accept: application/json' --data-urlencode "sysparm_query=name=InfraSupport_Dist-WindowsHK_L2_ASIA" --data-urlencode "sysparm_fields=sys_id,name,active" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/service_offering" -H 'Accept: application/json' --data-urlencode "sysparm_query=assignment_group.name=InfraSupport_Dist-WindowsHK_L2_ASIA^ORsupport_group.name=InfraSupport_Dist-WindowsHK_L2_ASIA" --data-urlencode "sysparm_fields=sys_id,name,parent,u_environment,operational_status" --data-urlencode "sysparm_display_value=true" --data-urlencode "sysparm_limit=50" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/service_offering" -H 'Accept: application/json' --data-urlencode "sysparm_query=assignment_group.name=InfraSupport_Dist-WindowsHK_L2_ASIA^ORsupport_group.name=InfraSupport_Dist-WindowsHK_L2_ASIA^u_environmentLIKEDevelopment" --data-urlencode "sysparm_fields=sys_id,name,parent,u_environment" --data-urlencode "sysparm_display_value=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/sys_choice" -H 'Accept: application/json' --data-urlencode "sysparm_query=name=incident^element=u_environment^inactive=false" --data-urlencode "sysparm_fields=label,value" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/core_company" -H 'Accept: application/json' --data-urlencode "sysparm_query=nameLIKEHONG KONG^nameLIKEAXA" --data-urlencode "sysparm_fields=sys_id,name" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/incident" -H 'Accept: application/json' --data-urlencode "sysparm_query=correlation_id=REPLACE_WITH_PROBLEM_ID" --data-urlencode "sysparm_fields=number,state,active,correlation_id,cmdb_ci,u_business_service,u_configuration_item,assignment_group,u_environment,company,short_description" --data-urlencode "sysparm_display_value=true" | jq '.result'
curl -s -u 'Tech_DynatraceJP_WS:JGyUG4XW^h^zCaW.U*(_Wnt0{+=XIqwNkL(pF*Z}' -G "https://silvastg.service-now.com/api/now/v2/table/incident" -H 'Accept: application/json' --data-urlencode "sysparm_query=u_configuration_item=1dfdcf8adb8dfa40251af9971d961941^sys_created_by=Tech_DynatraceJP_WS^ORDERBYDESCsys_created_on" --data-urlencode "sysparm_fields=number,correlation_id,cmdb_ci,u_business_service,sys_created_on" --data-urlencode "sysparm_display_value=true" --data-urlencode "sysparm_limit=5" | jq '.result'
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/33-verify-queries-p261090-cmdb-ci" "/Users/k/Work/AIProjects/Files/2026-10-01/"
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/33-verify-queries-p261090-cmdb-ci" "/Users/k/Codes/Pra/P1GithubActions/P1Gactions/app/Adocs/2026-10-01/"
