# DQL regex unclosed-group fix — paste into Dynatrace Logs and Events → Advanced mode (read-only)
# Corrected full query — 65 unique fields, HULFT host group
fetch logs, from: now()-24h | filter matchesValue(dt.host_group.id, "C_ALJ_BU_BAP_A_HULFT_E_PRD_T_APP") | filter matchesRegex(content, "(?i)(uketorininName1|uketorininKname1|uketorininName2|uketorininKname2|holderName|holderKname|holderAddress1|holderAddress2|holderAddress3|holderAddress4|holderKaddress1|holderKaddress2|holderKaddress3|holderKaddress4|insuredName|insuredKname|yokishaKname|yokishaName|ginkouName|bhidertVouzaNo|sourceIp|cleansingMojiName|requesterName|requesterId|policyHolderBirthDate|holderNameKana|telephoneNumber|holderKaddress|holderTel|holderZipCode|systemKbn|policyHolderName|mail|employeeNameKana|locationAddress1|locationAddress2|salesSupervisorEmployeeName|odsUserId|oneGenAgoName|oneGenAgoOdsUserId|twoGenAgoName|twoGenAgoOdsUserId|marketStrategyCustomer|name|given_name|family_name|branchCode|BranchName|policyOwnerNameKana|policyOwnerDateOfBirth|bankOwnerNameKana|bankCode|bankName|branchName|subscriberGender|subscriberDOB|subscriberAddr|subscriberPh|insuredGender|insuredDOB|personKanaName|subscriberZipCode|kanaFullAddress|kanjiFullAddress|displayName|loginId|lastName)") | summarize hit_count = count(), by: { host.name, log.source } | sort hit_count desc | limit 50
# Sample with value after key — limit 10
fetch logs, from: now()-24h | filter matchesValue(dt.host_group.id, "C_ALJ_BU_BAP_A_HULFT_E_PRD_T_APP") | filter matchesRegex(content, "(?i)(holderName|insuredName|loginId|mail|subscriberPh)[=:\\s]+\\S+") | fields timestamp, host.name, log.source, content | limit 10
# Option A1 — names group
fetch logs, from: now()-24h | filter matchesValue(dt.host_group.id, "C_ALJ_BU_BAP_A_HULFT_E_PRD_T_APP") | filter matchesRegex(content, "(?i)(uketorininName1|uketorininKname1|uketorininName2|uketorininKname2|holderName|holderKname|holderNameKana|insuredName|insuredKname|yokishaKname|yokishaName|cleansingMojiName|requesterName|policyHolderName|employeeNameKana|salesSupervisorEmployeeName|oneGenAgoName|twoGenAgoName|given_name|family_name|policyOwnerNameKana|bankOwnerNameKana|personKanaName|displayName|lastName|name)") | summarize hit_count = count(), by: { host.name, log.source } | sort hit_count desc | limit 50
# Option A2 — addresses group
fetch logs, from: now()-24h | filter matchesValue(dt.host_group.id, "C_ALJ_BU_BAP_A_HULFT_E_PRD_T_APP") | filter matchesRegex(content, "(?i)(holderAddress1|holderAddress2|holderAddress3|holderAddress4|holderKaddress1|holderKaddress2|holderKaddress3|holderKaddress4|holderKaddress|locationAddress1|locationAddress2|subscriberAddr|kanaFullAddress|kanjiFullAddress|holderZipCode|subscriberZipCode)") | summarize hit_count = count(), by: { host.name, log.source } | sort hit_count desc | limit 50
# Option A3 — IDs bank phone email DOB gender group
fetch logs, from: now()-24h | filter matchesValue(dt.host_group.id, "C_ALJ_BU_BAP_A_HULFT_E_PRD_T_APP") | filter matchesRegex(content, "(?i)(ginkouName|bhidertVouzaNo|sourceIp|requesterId|systemKbn|odsUserId|oneGenAgoOdsUserId|twoGenAgoOdsUserId|marketStrategyCustomer|branchCode|BranchName|bankCode|bankName|branchName|telephoneNumber|holderTel|subscriberPh|mail|loginId|policyHolderBirthDate|policyOwnerDateOfBirth|subscriberDOB|insuredDOB|subscriberGender|insuredGender)") | summarize hit_count = count(), by: { host.name, log.source } | sort hit_count desc | limit 50
# Option B — matchesPhrase or chain (subset)
fetch logs, from: now()-24h | filter matchesValue(dt.host_group.id, "C_ALJ_BU_BAP_A_HULFT_E_PRD_T_APP") | filter matchesPhrase(content, "holderName") or matchesPhrase(content, "insuredName") or matchesPhrase(content, "loginId") or matchesPhrase(content, "mail") or matchesPhrase(content, "subscriberPh") or matchesPhrase(content, "kanjiFullAddress") or matchesPhrase(content, "policyHolderBirthDate") | summarize hit_count = count(), by: { host.name, log.source } | sort hit_count desc | limit 50
# Option C — single field phrase count
fetch logs, from: now()-24h | filter matchesValue(dt.host_group.id, "C_ALJ_BU_BAP_A_HULFT_E_PRD_T_APP") | filter matchesPhrase(content, "holderName") | summarize hit_count = count(), by: { host.name, log.source } | sort hit_count desc | limit 50
