echo "Architecture doc: /Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/20-dynatrace-snow-pd-architecture/20-dynatrace-snow-pd-architecture.md"
echo "Workflow YAML pack: /Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/19-snow-connector-workflow-again/"
echo "OPEN: 1-open-snow-connector-and-pd.workflow.yaml"
echo "CLOSE: 2-close-snow-connector-and-pd.workflow.yaml"
echo "Connection URL example: https://silvastg.service-now.com"
echo "Allowlist: silvastg.service-now.com and events.pagerduty.com"
echo "Classic servicenowstg: ITSM OFF if Connector creates INC"
echo "Sync key: dt-problem-<problemId>"
ls "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/20-dynatrace-snow-pd-architecture"
ls "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/19-snow-connector-workflow-again"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" add "app/Adocs/2026-09-17/20-dynatrace-snow-pd-architecture"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" status --short "app/Adocs/2026-09-17/20-dynatrace-snow-pd-architecture"
echo "Do not commit/push unless user asks"
