export SILVA="https://silvastg.service-now.com"
export SNOW_AUTH='Tech_DynatraceJP_WS:<password>'
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/incident" --data-urlencode "sysparm_query=number=INC30340215" --data-urlencode "sysparm_fields=number,caller_id,u_on_behalf_of,contact_type,company,u_environment,business_service,service_offering,cmdb_ci,category,subcategory,impact,urgency,assignment_group,state,close_code,correlation_id" --data-urlencode "sysparm_display_value=all" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/sys_user" --data-urlencode "sysparm_query=nameLIKEDynatrace^ORuser_nameLIKEDynatrace" --data-urlencode "sysparm_fields=sys_id,name,user_name,active" --data-urlencode "sysparm_limit=10" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/sys_choice" --data-urlencode "sysparm_query=name=incident^element=u_environment^inactive=false" --data-urlencode "sysparm_fields=value,label" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/sys_choice" --data-urlencode "sysparm_query=name=incident^element=contact_type^inactive=false" --data-urlencode "sysparm_fields=value,label" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/sys_choice" --data-urlencode "sysparm_query=name=incident^element=category^inactive=false" --data-urlencode "sysparm_fields=value,label" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/sys_choice" --data-urlencode "sysparm_query=name=incident^element=subcategory^inactive=false^dependent_value=other" --data-urlencode "sysparm_fields=value,label,dependent_value" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/sys_choice" --data-urlencode "sysparm_query=name=incident^element=impact^inactive=false" --data-urlencode "sysparm_fields=value,label" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/sys_choice" --data-urlencode "sysparm_query=name=incident^element=urgency^inactive=false" --data-urlencode "sysparm_fields=value,label" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/sys_choice" --data-urlencode "sysparm_query=name=incident^element=state^inactive=false" --data-urlencode "sysparm_fields=value,label" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/sys_choice" --data-urlencode "sysparm_query=name=incident^element=close_code^inactive=false" --data-urlencode "sysparm_fields=value,label" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/cmdb_ci_service" --data-urlencode "sysparm_query=name=QA Platforms" --data-urlencode "sysparm_fields=sys_id,name,number,assignment_group,support_group,company" --data-urlencode "sysparm_display_value=all" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/service_offering" --data-urlencode "sysparm_query=parent.name=QA Platforms" --data-urlencode "sysparm_fields=sys_id,name,u_environment,operational_status" --data-urlencode "sysparm_display_value=all" --data-urlencode "sysparm_limit=50" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/sys_user_group" --data-urlencode "sysparm_query=name=AGS_FR_QAS_Service-Managers^ORname=Ops_Middleware_Monitoring_AXAJP^ORname=Database_AXAJP" --data-urlencode "sysparm_fields=sys_id,name,active" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/core_company" --data-urlencode "sysparm_query=name=AXA GROUP OPERATIONS" --data-urlencode "sysparm_fields=sys_id,name" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/cmdb_ci_service" --data-urlencode "sysparm_query=nameLIKEAGPO" --data-urlencode "sysparm_fields=sys_id,name,number,assignment_group" --data-urlencode "sysparm_display_value=all" --data-urlencode "sysparm_limit=20" | python3 -m json.tool
curl -s -u "$SNOW_AUTH" -G "$SILVA/api/now/v2/table/incident" --data-urlencode "sysparm_query=correlation_id=P-260916863" --data-urlencode "sysparm_fields=number,state,active,assignment_group" --data-urlencode "sysparm_display_value=all" | python3 -m json.tool
curl -s -X POST "https://events.pagerduty.com/v2/enqueue" -H "Content-Type: application/json" -d '{"routing_key":"<ROUTING_KEY>","event_action":"trigger","dedup_key":"dt-problem-TEST-1","payload":{"summary":"test from curl","source":"manual","severity":"info"}}'
curl -s -X POST "https://events.pagerduty.com/v2/enqueue" -H "Content-Type: application/json" -d '{"routing_key":"<ROUTING_KEY>","event_action":"resolve","dedup_key":"dt-problem-TEST-1"}'
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/7-query-silva-payload-values" "/Users/k/Work/AIProjects/Files/2026-10-01/"
cp -R "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-10-01/7-query-silva-payload-values" "/Users/k/Codes/Pra/P1GithubActions/P1Gactions/app/Adocs/2026-10-01/"
