curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/incident?sysparm_query=number=INC30339677&sysparm_display_value=true&sysparm_fields=number,sys_id,state,correlation_id,assignment_group,business_service,service_offering,short_description"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/incident?sysparm_query=correlation_id=P-260915247&sysparm_fields=number,sys_id,state,correlation_id"
curl -s -X POST -H "Authorization: Api-Token __DT_API_TOKEN__" -H "Content-Type: application/json" "https://__DT_TENANT__.live.dynatrace.com/api/v2/problems/-7958242114081464045_1790571960000V2/close" -d '{"message":"Closing test problem P-260915247 to trigger SILVA and PagerDuty close sync."}'
curl -s -H "Authorization: Api-Token __DT_API_TOKEN__" "https://__DT_TENANT__.live.dynatrace.com/api/v2/problems/-7958242114081464045_1790571960000V2?fields=+evidenceDetails"
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -X PATCH -H "Content-Type: application/json" -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/incident/__SYS_ID__" -d '{"state":"6","close_code":"Solved (Permanently)","close_notes":"Test ticket for Dynatrace and PagerDuty integration. No action needed.","comments":"Test ticket from Dynatrace problem P-260915247. Closing."}'
curl -s -X POST -H "Content-Type: application/json" "https://events.pagerduty.com/v2/enqueue" -d '{"routing_key":"__PD_ROUTING_KEY__","event_action":"resolve","dedup_key":"dt-problem-P-260915247"}'
curl -s -u 'Tech_DynatraceJP_WS:__SNOW_PASSWORD__' -H "Accept: application/json" "https://silvastg.service-now.com/api/now/v2/table/incident?sysparm_query=number=INC30339677&sysparm_display_value=true&sysparm_fields=number,state,close_code,close_notes,resolved_at"
cd /Users/k/Codes/Pra/P1GithubActions/P1Gactions && git add app/Adocs/2026-09-28/10-close-inc30339677-workflow-ticket
cd /Users/k/Codes/Pra/P1GithubActions/P1Gactions && git commit -m "Add guide for closing workflow-created INC30339677"
cd /Users/k/Codes/Pra/P1GithubActions/P1Gactions && git push
