echo "Example explain: /Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-23/5-sre-agent-teams-fake-example-explain/5-sre-agent-teams-fake-example-explain.md"
ls "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-23/5-sre-agent-teams-fake-example-explain"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" add "app/Adocs/2026-09-23/5-sre-agent-teams-fake-example-explain"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" status --short "app/Adocs/2026-09-23/5-sre-agent-teams-fake-example-explain"
echo "Do not commit/push unless user asks"
