echo "Detailed example: /Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/31-four-tools-detailed-example/31-four-tools-detailed-example.md"
echo "Short parent: /Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/26-four-tools-common-example/26-four-tools-common-example.md"
ls "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-09-17/31-four-tools-detailed-example"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" add "app/Adocs/2026-09-17/31-four-tools-detailed-example" "app/Adocs/2026-09-17/26-four-tools-common-example"
git -C "/Users/k/Codes/Pra/P1GithubActions/P1Gactions" status --short "app/Adocs/2026-09-17/31-four-tools-detailed-example"
echo "Do not commit/push unless user asks"
