# DQL PII discovery — paste into Dynatrace Logs and Events → Advanced mode (read-only)
# Step 0 inventory — all hosts in expanded spreadsheet (24h)
fetch logs, from: now()-24h | filter in(host.name, {"CEAA0059.PRPRIVMGMT.intra","CEAA006B.PRPRIVMGMT.intra","CEAA006F.PRPRIVMGMT.intra","CEAA007F.PRPRIVMGMT.intra","CEAA0080.PRPRIVMGMT.intra","CEAA0081.PRPRIVMGMT.intra","CEAA0088.PRPRIVMGMT.intra","CEAA008F.PRPRIVMGMT.intra","CEAA0090.PRPRIVMGMT.intra","CEAA0091.PRPRIVMGMT.intra","CEAA0092.PRPRIVMGMT.intra","CEAA101D.PRPRIVMGMT.intra","CEAA204E.prprivmgmt.intra","CEAA204F.prprivmgmt.intra","CEAA2090.prprivmgmt.intra","CEAA20B8.prprivmgmt.intra","CEAA20CB.prprivmgmt.intra","CEAA20CC.prprivmgmt.intra","CEAA20F7.prprivmgmt.intra","CEAA2115.prprivmgmt.intra","CEAA2116.prprivmgmt.intra","CEAA309A.prprivmgmt.intra","CEAA309B.prprivmgmt.intra","CEAA309C.prprivmgmt.intra","CEAA30A3.prprivmgmt.intra","CEAA30A6.prprivmgmt.intra","CEAA30AB.prprivmgmt.intra"}) | summarize log_count = count(), by: {host.name, log.source} | sort log_count desc
# Combined keyword sweep — all hosts (24h)
fetch logs, from: now()-24h | filter in(host.name, {"CEAA0059.PRPRIVMGMT.intra","CEAA006B.PRPRIVMGMT.intra","CEAA006F.PRPRIVMGMT.intra","CEAA007F.PRPRIVMGMT.intra","CEAA0080.PRPRIVMGMT.intra","CEAA0081.PRPRIVMGMT.intra","CEAA0088.PRPRIVMGMT.intra","CEAA008F.PRPRIVMGMT.intra","CEAA0090.PRPRIVMGMT.intra","CEAA0091.PRPRIVMGMT.intra","CEAA0092.PRPRIVMGMT.intra","CEAA101D.PRPRIVMGMT.intra","CEAA204E.prprivmgmt.intra","CEAA204F.prprivmgmt.intra","CEAA2090.prprivmgmt.intra","CEAA20B8.prprivmgmt.intra","CEAA20CB.prprivmgmt.intra","CEAA20CC.prprivmgmt.intra","CEAA20F7.prprivmgmt.intra","CEAA2115.prprivmgmt.intra","CEAA2116.prprivmgmt.intra","CEAA309A.prprivmgmt.intra","CEAA309B.prprivmgmt.intra","CEAA309C.prprivmgmt.intra","CEAA30A3.prprivmgmt.intra","CEAA30A6.prprivmgmt.intra","CEAA30AB.prprivmgmt.intra"}) | filter matchesRegex(content, "(?i)(EMPLID|customer_id|taxpayer_id|insuredPerson|loginId|displayName|password|passwd|Bearer)") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc | limit 50
# People Soft HR — count CEAA0059
fetch logs, from: now()-24h | filter host.name == "CEAA0059.PRPRIVMGMT.intra" | filter matchesRegex(content, "(?i)(EMPLID|employee_id|@|\\b\\d{12}\\b)") | summarize hit_count = count(), by: {log.source} | sort hit_count desc
# People Soft HR — sample EMPLID limit 10
fetch logs, from: now()-24h | filter host.name == "CEAA0059.PRPRIVMGMT.intra" | filter matchesRegex(content, "(?i)EMPLID[=:\\s]+[A-Z0-9]+") | fields timestamp, log.source, content | limit 10
# Customer MDM — all MDM hosts count
fetch logs, from: now()-24h | filter in(host.name, {"CEAA006B.PRPRIVMGMT.intra","CEAA2115.prprivmgmt.intra","CEAA2116.prprivmgmt.intra"}) | filter matchesRegex(content, "(?i)(customer_id|CUST_ID|insuredPerson|kanjiFullAddress|loginId|@)") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc
# Customer MDM — sample customer_id limit 10
fetch logs, from: now()-24h | filter host.name == "CEAA2115.prprivmgmt.intra" | filter matchesRegex(content, "(?i)customer_id[=:\\s]+\\S+") | fields timestamp, log.source, content | limit 10
# Tax Payment — APP and DB count
fetch logs, from: now()-24h | filter in(host.name, {"CEAA0088.PRPRIVMGMT.intra","CEAA30A3.prprivmgmt.intra"}) | filter matchesRegex(content, "(?i)(taxpayer_id|account_no|TIN|\\b\\d{12}\\b)") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc
# Tax Payment — sample limit 10
fetch logs, from: now()-24h | filter host.name == "CEAA0088.PRPRIVMGMT.intra" | filter matchesRegex(content, "(?i)taxpayer_id[=:\\s]+\\S+") | fields timestamp, log.source, content | limit 10
# imageWARE — count all four hosts
fetch logs, from: now()-24h | filter in(host.name, {"CEAA008F.PRPRIVMGMT.intra","CEAA0090.PRPRIVMGMT.intra","CEAA0091.PRPRIVMGMT.intra","CEAA0092.PRPRIVMGMT.intra"}) | filter matchesRegex(content, "(?i)(form_data|applicant_name|address|postal_code|insuredPerson|@)") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc
# Filenet — APP and DB count
fetch logs, from: now()-24h | filter in(host.name, {"CEAA20F7.prprivmgmt.intra","CEAA309B.prprivmgmt.intra","CEAA309C.prprivmgmt.intra"}) | filter matchesRegex(content, "(?i)(policy|claim|insured|document_id|loginId|customer_id)") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc
# ETL — APP and DB count
fetch logs, from: now()-24h | filter in(host.name, {"CEAA204E.prprivmgmt.intra","CEAA204F.prprivmgmt.intra","CEAA2090.prprivmgmt.intra","CEAA309A.prprivmgmt.intra"}) | filter matchesRegex(content, "(?i)(customer_id|EMPLID|password|jdbc|/[^\\s]+\\.(csv|txt|xml))") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc
# HULFT — count three hosts
fetch logs, from: now()-24h | filter in(host.name, {"CEAA007F.PRPRIVMGMT.intra","CEAA0080.PRPRIVMGMT.intra","CEAA0081.PRPRIVMGMT.intra"}) | filter matchesRegex(content, "(?i)(password|passwd|user\\s*=|/[^\\s]+\\.(csv|txt|xml|dat))") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc
# Host group MDM cluster C_ALJ_BU_DATA-INNOVATION_A_MDM_E_PRD_T_BASE
fetch logs, from: now()-24h | filter matchesValue(dt.host_group.id, "C_ALJ_BU_DATA-INNOVATION_A_MDM_E_PRD_T_BASE") | filter matchesRegex(content, "(?i)(customer_id|CUST_ID|insuredPerson|kanjiFullAddress|loginId|@)") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc
# All host groups expanded — @ symbol count
fetch logs, from: now()-24h | filter in(dt.host_group.id, {"C_ALJ_BU_OS_A_INFRA_E_PRD_T_BASE","C_ALJ_BU_BAP_A_HULFT_E_PRD_T_APP","C_ALJ_BU_BAP_A_TAX-PAYMENT_E_PRD_T_APP","C_ALJ_BU_BAP_A_TAX-PAYMENT_E_PRD_T_DB","C_ALJ_BU_MIDDLEWARE-SHARED-PRODUCT_A","C_ALJ_BU_DATA-INNOVATION_A_MDM_E_PRD_T_BASE","C_ALJ_BU_CLAIMS-RECEPTION_A_ICM_E_PRD_T_APP","C_ALJ_BU_CLAIMS-RECEPTION_A_ICM_E_PRD_T_DB"}) | filter matchesPhrase(content, "@") | summarize hit_count = count(), by: {dt.host_group.id, host.name, log.source} | sort hit_count desc | limit 50
# Insurance field sweep seq 7 — 20 keys on high-risk hosts
fetch logs, from: now()-24h | filter in(host.name, {"CEAA006B.PRPRIVMGMT.intra","CEAA2115.prprivmgmt.intra","CEAA2116.prprivmgmt.intra","CEAA008F.PRPRIVMGMT.intra","CEAA0090.PRPRIVMGMT.intra","CEAA0091.PRPRIVMGMT.intra","CEAA0092.PRPRIVMGMT.intra","CEAA20F7.prprivmgmt.intra"}) | filter matchesRegex(content, "(?i)(insuredPerson|subscriberGender|subscriberDOB|subscriberAddr|subscriberPh|insuredGender|insuredDOB|insuredPersonKanjiName|insuredPersonKanaName|contractPersonKanjiName|contractPersonKanaName|subscriberZipCode|kanaFullAddress|kanjiFullAddress|displayName|loginId|lastName|lastNameKana|\\bdob\\b|telNumberOld)") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc | limit 50
# Japan mobile phone 090/080/070 — HR and MDM hosts
fetch logs, from: now()-24h | filter in(host.name, {"CEAA0059.PRPRIVMGMT.intra","CEAA006B.PRPRIVMGMT.intra","CEAA2115.prprivmgmt.intra","CEAA2116.prprivmgmt.intra"}) | filter matchesRegex(content, "\\b0[789]0\\d{8}\\b") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc
# Email — count all inventory hosts
fetch logs, from: now()-24h | filter in(host.name, {"CEAA0059.PRPRIVMGMT.intra","CEAA006B.PRPRIVMGMT.intra","CEAA006F.PRPRIVMGMT.intra","CEAA007F.PRPRIVMGMT.intra","CEAA0080.PRPRIVMGMT.intra","CEAA0081.PRPRIVMGMT.intra","CEAA0088.PRPRIVMGMT.intra","CEAA008F.PRPRIVMGMT.intra","CEAA0090.PRPRIVMGMT.intra","CEAA0091.PRPRIVMGMT.intra","CEAA0092.PRPRIVMGMT.intra","CEAA101D.PRPRIVMGMT.intra","CEAA204E.prprivmgmt.intra","CEAA204F.prprivmgmt.intra","CEAA2090.prprivmgmt.intra","CEAA20B8.prprivmgmt.intra","CEAA20CB.prprivmgmt.intra","CEAA20CC.prprivmgmt.intra","CEAA20F7.prprivmgmt.intra","CEAA2115.prprivmgmt.intra","CEAA2116.prprivmgmt.intra","CEAA309A.prprivmgmt.intra","CEAA309B.prprivmgmt.intra","CEAA309C.prprivmgmt.intra","CEAA30A3.prprivmgmt.intra","CEAA30A6.prprivmgmt.intra","CEAA30AB.prprivmgmt.intra"}) | filter matchesRegex(content, "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc | limit 50
# Password token Bearer — all inventory hosts
fetch logs, from: now()-24h | filter in(host.name, {"CEAA0059.PRPRIVMGMT.intra","CEAA006B.PRPRIVMGMT.intra","CEAA006F.PRPRIVMGMT.intra","CEAA007F.PRPRIVMGMT.intra","CEAA0080.PRPRIVMGMT.intra","CEAA0081.PRPRIVMGMT.intra","CEAA0088.PRPRIVMGMT.intra","CEAA008F.PRPRIVMGMT.intra","CEAA0090.PRPRIVMGMT.intra","CEAA0091.PRPRIVMGMT.intra","CEAA0092.PRPRIVMGMT.intra","CEAA101D.PRPRIVMGMT.intra","CEAA204E.prprivmgmt.intra","CEAA204F.prprivmgmt.intra","CEAA2090.prprivmgmt.intra","CEAA20B8.prprivmgmt.intra","CEAA20CB.prprivmgmt.intra","CEAA20CC.prprivmgmt.intra","CEAA20F7.prprivmgmt.intra","CEAA2115.prprivmgmt.intra","CEAA2116.prprivmgmt.intra","CEAA309A.prprivmgmt.intra","CEAA309B.prprivmgmt.intra","CEAA309C.prprivmgmt.intra","CEAA30A3.prprivmgmt.intra","CEAA30A6.prprivmgmt.intra","CEAA30AB.prprivmgmt.intra"}) | filter matchesRegex(content, "(?i)(password|passwd|token|Bearer)\\s*[=:]\\s*\\S+") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc | limit 50
# My Number 12-digit — high-PII hosts count
fetch logs, from: now()-24h | filter in(host.name, {"CEAA0059.PRPRIVMGMT.intra","CEAA006B.PRPRIVMGMT.intra","CEAA0088.PRPRIVMGMT.intra","CEAA30A3.prprivmgmt.intra"}) | filter matchesRegex(content, "\\b\\d{12}\\b") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc
# EIP CEAA006F — error payload count
fetch logs, from: now()-24h | filter host.name == "CEAA006F.PRPRIVMGMT.intra" | filter matchesRegex(content, "(?i)(error|exception|payload|customer_id|EMPLID)") | summarize hit_count = count(), by: {log.source} | sort hit_count desc
# Load Runner CEAA20CB CEAA20CC — test data check
fetch logs, from: now()-24h | filter in(host.name, {"CEAA20CB.prprivmgmt.intra","CEAA20CC.prprivmgmt.intra"}) | filter matchesRegex(content, "(?i)(password|customer_id|@)") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc
# Weekly sweep — inventory 7d summarize only
fetch logs, from: now()-7d | filter in(host.name, {"CEAA0059.PRPRIVMGMT.intra","CEAA006B.PRPRIVMGMT.intra","CEAA006F.PRPRIVMGMT.intra","CEAA007F.PRPRIVMGMT.intra","CEAA0080.PRPRIVMGMT.intra","CEAA0081.PRPRIVMGMT.intra","CEAA0088.PRPRIVMGMT.intra","CEAA008F.PRPRIVMGMT.intra","CEAA0090.PRPRIVMGMT.intra","CEAA0091.PRPRIVMGMT.intra","CEAA0092.PRPRIVMGMT.intra","CEAA101D.PRPRIVMGMT.intra","CEAA204E.prprivmgmt.intra","CEAA204F.prprivmgmt.intra","CEAA2090.prprivmgmt.intra","CEAA20B8.prprivmgmt.intra","CEAA20CB.prprivmgmt.intra","CEAA20CC.prprivmgmt.intra","CEAA20F7.prprivmgmt.intra","CEAA2115.prprivmgmt.intra","CEAA2116.prprivmgmt.intra","CEAA309A.prprivmgmt.intra","CEAA309B.prprivmgmt.intra","CEAA309C.prprivmgmt.intra","CEAA30A3.prprivmgmt.intra","CEAA30A6.prprivmgmt.intra","CEAA30AB.prprivmgmt.intra"}) | filter matchesPhrase(content, "@") | summarize hit_count = count(), by: {host.name, log.source} | sort hit_count desc | limit 50
