# Find HATS rawDataList PII — paste into Dynatrace Logs and Events → Advanced mode (read-only)
# Query A — count per host group
fetch logs, from: now()-24h | filter in(dt.host_group.id, { "C_ALJ_BU_MIDDLEWARE-SHARED-PRODUCT_A_HATS_E_PRD_T_APP", "C_ALJ_BU_DATAENGLF_A_CUSTMDMGM_E_PRD_T_APP" }) | filter matchesValue(log.source, "SystemOut") | filter matchesPhrase(content, "ProcessNdServiceImpl") or matchesPhrase(content, "HatsProcessResponse") or matchesPhrase(content, "rawDataList") | summarize hit_count = count(), by: { dt.host_group.id } | sort hit_count desc
# Query B — drill-down by host.name + log.source
fetch logs, from: now()-24h | filter in(dt.host_group.id, { "C_ALJ_BU_MIDDLEWARE-SHARED-PRODUCT_A_HATS_E_PRD_T_APP", "C_ALJ_BU_DATAENGLF_A_CUSTMDMGM_E_PRD_T_APP" }) | filter matchesValue(log.source, "SystemOut") | filter matchesPhrase(content, "ProcessNdServiceImpl") or matchesPhrase(content, "HatsProcessResponse") or matchesPhrase(content, "rawDataList") | summarize hit_count = count(), by: { dt.host_group.id, host.name, log.source } | sort hit_count desc
# Query C — rawDataList + Japanese Unicode
fetch logs, from: now()-24h | filter in(dt.host_group.id, { "C_ALJ_BU_MIDDLEWARE-SHARED-PRODUCT_A_HATS_E_PRD_T_APP", "C_ALJ_BU_DATAENGLF_A_CUSTMDMGM_E_PRD_T_APP" }) | filter matchesValue(log.source, "SystemOut") | filter matchesPhrase(content, "rawDataList") | filter matchesRegex(content, "[\x{3040}-\x{309F}\x{30A0}-\x{30FF}\x{4E00}-\x{9FFF}]") | summarize hit_count = count(), by: { dt.host_group.id, host.name, log.source } | sort hit_count desc
# Query C fallback — phrase-based PII labels
fetch logs, from: now()-24h | filter in(dt.host_group.id, { "C_ALJ_BU_MIDDLEWARE-SHARED-PRODUCT_A_HATS_E_PRD_T_APP", "C_ALJ_BU_DATAENGLF_A_CUSTMDMGM_E_PRD_T_APP" }) | filter matchesValue(log.source, "SystemOut") | filter matchesPhrase(content, "rawDataList") | filter matchesPhrase(content, "保険金") or matchesPhrase(content, "健保") or matchesPhrase(content, "TXID") or matchesPhrase(content, "OPID") | summarize hit_count = count(), by: { dt.host_group.id } | sort hit_count desc
# Query D — sample full content HATS (limit 10)
fetch logs, from: now()-24h | filter matchesValue(dt.host_group.id, "C_ALJ_BU_MIDDLEWARE-SHARED-PRODUCT_A_HATS_E_PRD_T_APP") | filter matchesValue(log.source, "SystemOut") | filter matchesPhrase(content, "Finish ND processing") | filter matchesPhrase(content, "HatsProcessResponse") | filter matchesPhrase(content, "rawDataList") | fields timestamp, dt.host_group.id, dt.security_context, host.name, log.source, content | sort timestamp desc | limit 10
# Query D — sample full content CUSTMDMGM (limit 10)
fetch logs, from: now()-24h | filter matchesValue(dt.host_group.id, "C_ALJ_BU_DATAENGLF_A_CUSTMDMGM_E_PRD_T_APP") | filter matchesValue(log.source, "SystemOut") | filter matchesPhrase(content, "Finish ND processing") or matchesPhrase(content, "HatsProcessResponse") or matchesPhrase(content, "rawDataList") | fields timestamp, dt.host_group.id, dt.security_context, host.name, log.source, content | sort timestamp desc | limit 10
# Query E — filter by dt.security_context
fetch logs, from: now()-24h | filter in(dt.security_context, { "ALJ-MIDDLEWARE-SHARED-PRODUCT-HATS-P", "ALJ-DATAENGLF-CUSTMDMGM-PRD" }) | filter matchesValue(log.source, "SystemOut") | filter matchesPhrase(content, "rawDataList") | summarize hit_count = count(), by: { dt.host_group.id, dt.security_context, log.source } | sort hit_count desc
# Query F — widest net: ProcessNdServiceImpl only (1h window)
fetch logs, from: now()-1h | filter matchesValue(dt.host_group.id, "C_ALJ_BU_MIDDLEWARE-SHARED-PRODUCT_A_HATS_E_PRD_T_APP") | filter matchesValue(log.source, "SystemOut") | filter matchesPhrase(content, "ProcessNdServiceImpl") | summarize hit_count = count(), by: { host.name, log.source } | sort hit_count desc
# Append missing host groups to seq 11 unique.sh (do not run as DQL)
echo 'C_ALJ_BU_MIDDLEWARE-SHARED-PRODUCT_A_HATS_E_PRD_T_APP' >> "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-08-28/11-dql-pii-by-all-host-groups/unique.sh"
echo 'C_ALJ_BU_DATAENGLF_A_CUSTMDMGM_E_PRD_T_APP' >> "/Users/k/Learnings/AIProject/CursorFiles/Daily Files/2026-08-28/11-dql-pii-by-all-host-groups/unique.sh"
