ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/aws-neuron-efa
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/ml-capacity-block
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/wireguard-with-cilium
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/external-secrets
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/fargate-serverless
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/fully-private-cluster
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/ipv6-eks-cluster
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/istio
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/multi-tenancy-with-teams
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/private-public-ingress
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/stateful
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/tls-with-aws-pca-issuer
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/sso-okta
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/targeted-odcr
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/ecr-pull-through-cache
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/karpenter
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/karpenter-mng
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/multi-node-vllm
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/nvidia-gpu-efa
ls -la /Users/k/Codes/GithubProjects/Terraform/terraform-aws-eks-blueprints-main/patterns/sso-iam-identity-center
